# Generated by Django 5.0.6 on 2024-05-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('rainType', models.CharField(blank=True, max_length=20, null=True)),
                ('sky', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
